//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seminar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seminar()
        {
            this.Attendance = new HashSet<Attendance>();
        }
    
        public int SeminarID { get; set; }
        public string SeminarTitle { get; set; }
        public string SeminarTeacher { get; set; }
        public string SeminarRoom { get; set; }
        public System.DateTime SeminarDate { get; set; }
        public System.DateTime SeminarStartTime { get; set; }
        public System.DateTime SeminarEndTime { get; set; }
        public string SeminarDesc { get; set; }
        public string SeminarType { get; set; }
        public string IsAvailable { get; set; }
        public Nullable<int> OrganizerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual Organizer Organizer { get; set; }
    }
}
